function DadosDemo() {
    document.getElementById("info").innerHTML = `A região tem área de 1.558.000 km². Tem população absoluta de cerca de 57.071.564 milhões de habitantes e população relativa de cerca de 34,1 hab./km² Possui densidade demográfica de aproximadamente 36,63 hab./km², sendo ela bastante irregular, com presença maior de população e densidade demográfica no litoral. Detém taxa de natalidade de 13,3 por mil habitantes (2020) e taxa de mortalidade de 6,8 por mil habitantes (2020).`
}

function AspectosSocio() {
    document.getElementById("info").innerHTML = `Na Região Nordeste é possível identificar três tipos de climas: tropical, semiárido e equatorial úmido. A principal causa para a desertificação do Nordeste é o desmatamento desenfreado. A desertificação do solo é um dos problemas ambientais mais graves que afetam a região, além disso, o desmatamento e as queimadas da vegetação ocasionam na região uma série de consequências negativas, como a perda da biodiversidade, degradação do solo, processos erosivos, escoamento superficial, diminuição da água para recargas dos aquíferos, entre outras consequências. No setor de extração, o Nordeste se destaca na produção de petróleo e gás natural, produzidos na Bahia, Sergipe, Rio Grande do Norte, Piauí e Ceará. As atividades de agricultura e pecuária são as que trazem maior força econômica ao nordeste, no qual o cultivo de feijão, milho, arroz, café, coco, algodão, mandioca, sisal, banana e castanhas predominam e movimentam a economia.`;
}

function QuestAgro() {
    document.getElementById("info").innerHTML = `Boa parte das terras nordestinas pertencem a famílias com poder político e monetário, como no Sergipe, onde cerca de 70% das terras agricultáveis são propriedade da família Franco, que inicialmente teve participação política influente na região. Por conta disso, na região ocorrem muitos casos de latifúndios improdutivos e pouco acesso à terra. Além disso, o Nordeste é foco de disputas territoriais, que acontecem por conta da expansão da fronteira agrícola em direção ao norte do Brasil. Na questão agrária nordestina Elizabeth Teixeira foi muito influente, era trabalhadora rural e ativista das Ligas Camponesas que buscava a redistribuição das terras e reivindicação dos direitos trabalhistas, para garantir melhores condições de vida aos trabalhadores do campo. Tornou-se a principal representante das Ligas Camponesas na Paraíba, tendo como principal causa na luta agrária a remuneração dos trabalhadores rurais que não recebiam por seus trabalhos, ela relatou que os trabalhadores rurais cumpriam seus deveres de cuidar das terras, mas não recebiam salário, eram violentados e expulsos sem quaisquer direitos.`;
}

function DireitoDever() {
    document.getElementById("info").innerHTML = `Segunda o parágrafo 196 da Constituição brasileira, ter acesso à saúde é um direito de todos e um dever do Estado, portanto o Estado deve prover saúde à seu povo. Em 2019, de acordo com pesquisas do IBGE, cerca de 90% da população da região depende do Sistema Único de Saúde (SUS), e em uma pesquisa feito pelo O Globo/Ipec 79% das pessoas entrevistadas no nordeste dizem não ter plano de saúde, também 41% das pessoas consideram a saúde um dos maiores problemas enfrentados pelo Brasil. Além disso, existem poucos médicos para muitos pacientes, e cerca de 40% dos profissionais da saúde no Nordeste não possuem formação concluída, o que dificulta a atuação na área. Entretanto, o  município de Maceió é o 1º local entre as capitais nordestinas e o 4º nacionalmente com melhor desempenho no programa Previne Brasil, que determina a qualidade da Atenção Primária à Saúde no país, de forma que as vacinações são eficientes, tendo uma  gestão de remédios nas moradias, atendimento às comunidades vulneráveis, pronto socorro, agendamentos organizados de diferentes formas e melhoria geral nos postos de saúde pública, como o SUS. Além disso, no Nordeste o Centro Antiveneno da Bahia (CIAVE) é de extrema relevância no tratamento de envenenamentos e inalação de substâncias tóxicas.`;
}

function Pers() {
    document.getElementById("info").innerHTML = "Não foi feita uma biografia/vídeo sobre nenhuma personalidade nordestina, visto que as pessoas dessa região não têm muito reconhecimento nacional.";
}